set SPACEFISH_VI_MODE_SHOW true
set SPACEFISH_VI_MODE_INSERT "| "
set SPACEFISH_VI_MODE_NORMAL ""
set SPACEFISH_VI_MODE_VISUAL "= "
set SPACEFISH_VI_MODE_COLOR "cyan"
set SPACEFISH_VI_MODE_SUFFIX ""

set SPACEFISH_EXIT_CODE_SHOW true
set SPACEFISH_PROMPT_ADD_NEWLINE false
set SPACEFISH_PROMPT_SEPARATE_LINE false
set SPACEFISH_CHAR_SYMBOL ❯
set SPACEFISH_CHAR_SUFFIX " "
set SPACEFISH_PACKAGE_SHOW false
set SPACEFISH_NODE_SHOW false
set SPACEFISH_RUBY_SHOW false
set SPACEFISH_ELM_SHOW false
set SPACEFISH_ELIXIR_SHOW false
set SPACEFISH_GOLANG_SHOW false
set SPACEFISH_PHP_SHOW false
set SPACEFISH_RUST_SHOW false
set SPACEFISH_JULIA_SHOW false
set SPACEFISH_DOCKER_SHOW false
set SPACEFISH_DOCKER_CONTEXT_SHOW false
set SPACEFISH_AWS_SHOW false
set SPACEFISH_CONDA_SHOW false
set SPACEFISH_VENV_SHOW false
set SPACEFISH_PYENV_SHOW false
set SPACEFISH_DOTNET_SHOW false
set SPACEFISH_KUBECONTEXT_SHOW false
set SPACEFISH_JOBS_SHOW true
set SPACEFISH_EXEC_TIME_SHOW true
set SPACEFISH_EXEC_TIME_PREFIX ""
set SPACEFISH_EXEC_TIME_ELAPSED 1
set SPACEFISH_GIT_PREFIX ""
set SPACEFISH_HOST_SHOW true
set SPACEFISH_HOST_PREFIX "@"
set SPACEFISH_DIR_PREFIX ""
set SPACEFISH_DIR_TRUNC_PREFIX "…/"
set SPACEFISH_USER_SUFFIX ""
set SPACEFISH_USER_PREFIX ""
set SPACEFISH_PROMPT_ORDER  vi_mode time user host dir git package node ruby elixir golang php rust haskell julia docker aws venv conda pyenv dotnet exec_time line_sep battery exit_code jobs char
