require("startup").setup {
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            "      *#=+                    =+*%.   ",
            "    .%*+%=%+                :@=##=+-  ",
            "   =@=##=%-     :=++++=-.    .*-+%=%* ",
            "   -:%+*%.   .=##########+:    *%=%--.",
            "      :+    :##############=    -=    ",
            "            *#########***###:         ",
            "           .**######*******#-         ",
            "            +***************.         ",
            "     .-*.   .+*************:    ++.   ",
            "   +=#*+@-    -+*********-.    #*+%=+.",
            "   :%++==%+     .:----:.     -%:=+=@= ",
            "     *#=@=*+                -%=%+++.  ",
            "      =%:=                    --#*    "
        },
        highlight = "Number",
        default_color = "",
        oldfiles_amount = 0,
    },
    -- name which will be displayed and command
    body = {
        type = "oldfiles",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Recent files",
        margin = 5,
        content = {},
        highlight = "String",
        default_color = "",
        oldfiles_amount = 9,
    },

    options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 3, 2 },
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "body" },
}
